version: "3"

services:

  phoenix:
    container_name: phoenix
    build: 
      context: .
      dockerfile: DockerFile
    env_file:
      - docker.env
    environment:
      DATABASE_URL: postgres://cozajqbn:WAb-PavXlRQpqIGs17UnD8m1XckpJnEh@fanny.db.elephantsql.com/cozajqbn
      DATABASE_USER: cozajqbn
      DATABASE_PASS: WAb-PavXlRQpqIGs17UnD8m1XckpJnEh
      DATABASE_NAME: cozajqbn
      DATABASE_PORT: 5433
      DATABASE_HOST: fanny.db.elephantsql.com
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    working_dir: /app
    restart: always