version: "3"

services:
  phoenix:
    container_name: phoenix
    build: 
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    links: 
      - database
    depends_on: 
      - database
    working_dir: /app

  database:
    image: postgres:9.5
    container_name: database
    environment:
      POSTGRES_PASSWORD: "1234",
    volumes: 
      - ./database:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    restart: always