version: "3"

services:

  phoenix:
    container_name: phoenix
    build: 
      context: .
      dockerfile: DockerFile
    env_file:
      - docker.env
    environment:
      DATABASE_URL: DATABASE_URL
      DATABASE_USER: DATABASE_USER
      DATABASE_PASS: DATABASE_PASS
      DATABASE_NAME: DATABASE_NAME
      DATABASE_PORT: 5433
      DATABASE_HOST: DATABASE_HOST
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    working_dir: /app
    restart: always