version: "3"

services:

  phoenix:
    container_name: phoenix
    build: 
      context: .
      dockerfile: DockerFile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    links: 
      - database
    depends_on: 
      - database
    working_dir: /app
    restart: always

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      DATABASE_USER: postgres
      DATABASE_PASS: 1234
      DATABASE_NAME: todos
      DATABASE_PORT: 5432
      DATABASE_HOST: localhost
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports: 
        - 5432:5432