FROM elixir

RUN apt-get update && \
    sudo mix local.hex --force && \
    sudo mix archive.install hex phx_new 1.5.3 --force && \
    sudo mix local.rebar --force && \
    apt-get install -y postgresql-client && \
    apt-get install -y inotify-tools && \
    apt-get install -y nodejs && \
    curl -L https://npmjs.org/install.sh | sh

RUN mkdir /app

WORKDIR /app

EXPOSE 4000

CMD ["mix", "phx.server", "-p", "5433"]
