version: "3"

networks:
    internal:
      external: false

services:

  phoenix:
    container_name: phoenix
    build: 
      context: .
      dockerfile: DockerFile
    env_file:
      - docker.env
    environment:
      DATABASE_URL: DB_URL
      DATABASE_USER: DB_USERNAME
      DATABASE_PASS: DB_PASSWORD
      DATABASE_NAME: DB_USERNAME
      DATABASE_PORT: "5433"
      DATABASE_HOST: DB_HOST
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    links: 
      - database
    depends_on: 
      - database
    networks:
      - internal
    working_dir: /app
    restart: always

  database:
    container_name: database
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5433:5432"
    expose:
      - "5433"